/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultSlugRouteImport } from './routes/result.$slug'
import { Route as ApiPublicHooksSyncListingsRouteImport } from './routes/api/public/hooks/sync-listings'

const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultSlugRoute = ResultSlugRouteImport.update({
  id: '/result/$slug',
  path: '/result/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncListingsRoute =
  ApiPublicHooksSyncListingsRouteImport.update({
    id: '/api/public/hooks/sync-listings',
    path: '/api/public/hooks/sync-listings',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quiz': typeof QuizRoute
  '/result/$slug': typeof ResultSlugRoute
  '/api/public/hooks/sync-listings': typeof ApiPublicHooksSyncListingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quiz': typeof QuizRoute
  '/result/$slug': typeof ResultSlugRoute
  '/api/public/hooks/sync-listings': typeof ApiPublicHooksSyncListingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quiz': typeof QuizRoute
  '/result/$slug': typeof ResultSlugRoute
  '/api/public/hooks/sync-listings': typeof ApiPublicHooksSyncListingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quiz' | '/result/$slug' | '/api/public/hooks/sync-listings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quiz' | '/result/$slug' | '/api/public/hooks/sync-listings'
  id:
    | '__root__'
    | '/'
    | '/quiz'
    | '/result/$slug'
    | '/api/public/hooks/sync-listings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuizRoute: typeof QuizRoute
  ResultSlugRoute: typeof ResultSlugRoute
  ApiPublicHooksSyncListingsRoute: typeof ApiPublicHooksSyncListingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$slug': {
      id: '/result/$slug'
      path: '/result/$slug'
      fullPath: '/result/$slug'
      preLoaderRoute: typeof ResultSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-listings': {
      id: '/api/public/hooks/sync-listings'
      path: '/api/public/hooks/sync-listings'
      fullPath: '/api/public/hooks/sync-listings'
      preLoaderRoute: typeof ApiPublicHooksSyncListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuizRoute: QuizRoute,
  ResultSlugRoute: ResultSlugRoute,
  ApiPublicHooksSyncListingsRoute: ApiPublicHooksSyncListingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
